#!/bin/bash

if [ "$PASSWORD_IKR" == "" ] || [ "$PASSWORD_LESYA" == "" ]
then
    echo "Usage:"
    echo "$ PASSWORD_IKR=… PASSWORD_LESYA=… ./backup-to-this-vbox"
    exit 1
fi

rm -r /var/mail/ikr
rm -r /home/ikr/mail

doveadm -o imapc_host=mail.ikr.su -o imapc_port=993 -o "imapc_password=$PASSWORD_IKR" -o imapc_user=ikr -o imapc_ssl=imaps -o ssl_client_ca_dir=/etc/ssl/certs/ -o mail_fsync=never backup -R -u ikr imapc:

rm -r /var/mail/lesya
rm -r /home/lesya/mail

doveadm -o imapc_host=mail.ikr.su -o imapc_port=993 -o "imapc_password=$PASSWORD_LESYA" -o imapc_user=lesya -o imapc_ssl=imaps -o ssl_client_ca_dir=/etc/ssl/certs/ -o mail_fsync=never backup -R -u lesya imapc:

sudo -u ikr sshpass -p "$PASSWORD_IKR" scp -r ikr.su:/home/ikr/*.git /home/ikr
sudo -u ikr sshpass -p "$PASSWORD_IKR" scp -r ikr.su:/home/ikr/books /home/ikr
