#!/bin/bash

if [ "$PASSWORD_IKR" == "" ] || [ "$PASSWORD_LESYA" == "" ]
then
    echo "Usage:"
    echo "$ PASSWORD_IKR=… PASSWORD_LESYA=… ./backup-to-this-vbox"
    exit 1
fi

doveadm -o imapc_host=mail.ikr.su -o imapc_port=993 -o "imapc_password=$PASSWORD_IKR" -o imapc_user=ikr -o imapc_ssl=imaps -o ssl_client_ca_dir=/etc/ssl/certs/ -o mail_fsync=never -v backup -R -u ikr imapc:

doveadm -o imapc_host=mail.ikr.su -o imapc_port=993 -o "imapc_password=$PASSWORD_LESYA" -o imapc_user=lesya -o imapc_ssl=imaps -o ssl_client_ca_dir=/etc/ssl/certs/ -o mail_fsync=never -v backup -R -u lesya imapc:

rsync -avz -e "sshpass -p '$PASSWORD_IKR' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress ikr.su:/home/ikr/*.git /home/ikr
rsync -avz -e "sshpass -p '$PASSWORD_IKR' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress ikr.su:/home/ikr/books /home/ikr
rsync -avz -e "sshpass -p '$PASSWORD_IKR' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress ikr.su:/home/ikr/estimates-template /home/ikr
rsync -avz -e "sshpass -p '$PASSWORD_IKR' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress ikr.su:/home/ikr/react-* /home/ikr
rsync -avzl -e "sshpass -p '$PASSWORD_IKR' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress ikr.su:/var/www/heap/* /var/www/heap
